name: acrn
version: 2.3.0-core18
type: gadget
base: core18
summary: ACRN PC gadget
description: |
  PC gadget for ACRN devices.
grade: devel
confinement: strict

apps:
  acrn-dm:
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/x86_64-linux-gnu:$SNAP/lib/x86_64-linux-gnu:LD_LIBRARY_PATH
    command:
      usr/bin/acrn-dm

  acrnctl:
    command:
      usr/bin/acrnctl

parts:
  build-environ:
    # Install build tools and dependencies required by ACRN development
    # https://projectacrn.github.io/2.3/getting-started/building-from-source.html
    build-packages: [ gcc, git, make, libssl-dev, libpciaccess-dev, uuid-dev,
                      libsystemd-dev, libevent-dev, libxml2-dev, libusb-1.0-0-dev,
                      python3, python3-pip, libblkid-dev, e2fslibs-dev, pkg-config,
                      libnuma-dev, liblz4-tool, flex, bison ]
    plugin: python
    python-packages: [ kconfiglib ]
    stage-packages: [ grub-efi-amd64-signed, grub-pc-bin, shim-signed ]
    prime: [ usr/lib/grub/x86_64-efi/ ]

  iasl:
    after: [ build-environ ]
    plugin: make
    source: https://acpica.org/sites/acpica/files/acpica-unix-20191018.tar.gz
    make-parameters: [ iasl ]
    organize:
      usr/bin/iasl: usr/sbin/iasl
    prime:
      - usr/sbin/iasl

  acrn:
    after: [ iasl ]
    plugin: make
    source: https://github.com/projectacrn/acrn-hypervisor.git
    source-tag: v2.3
    stage-packages: [ libpciaccess-dev, libusb-1.0-0 ]
    override-prime: |
      snapcraftctl prime
      install -D $SNAPCRAFT_PART_BUILD/build/hypervisor/acrn.bin boot/acrn/acrn.bin

  grub:
    after: [ build-environ ]
    build-packages: [ grub-common ]
    plugin: make
    source: .
