name: acrn-uos
base: core20
summary: ACRN User VM
description: |
  User VM to be launched on ACRN
grade: devel
confinement: strict
adopt-info: uos

apps:
  xzcat:
    environment:
      LD_LIBRARY_PATH: $SNAP/lib/x86_64-linux-gnu:LD_LIBRARY_PATH
    command: usr/bin/xzcat

plugs:
  executables:
    interface: content
    target: $SNAP/bin

  uos:
    interface: content
    target: $SNAP_COMMON/uos

parts:
  environ:
    plugin: nil
    stage-packages: [ xz-utils, liblzma5 ]

  uos:
    after: [ environ ]
    plugin: dump
    source: src
    override-prime: |
      set -ex
      xzimg=$(basename `ls $SNAPCRAFT_PART_SRC/images/*.img.xz`)
      osname=${xzimg%.img.xz}
      snapcraftctl set-version $osname
      mkdir -p snap/hooks/
      sed -e 's/uos.img/'${xzimg%.xz}'/1' $SNAPCRAFT_PART_SRC/hooks/connect-plug-uos > snap/hooks/connect-plug-uos
      sed -e 's/uos.img/'${xzimg%.xz}'/1' $SNAPCRAFT_PART_SRC/launch.sh > launch_$osname.sh
      chmod a+rx snap/hooks/connect-plug-uos launch_$osname.sh
      cp $SNAPCRAFT_PART_SRC/images/$xzimg .
